### ISSUE TITLE
build issue in Scientific Liunx (RedHat) 6.4

### ISSUE THREAD

**Issue by dominicjob** [biolab-unige/nifti2dicom#32]
# make
Scanning dependencies of target nifti2dicom_core
[  2%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dVersion.cxx.o
[  5%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dToolsMetaDataDictionary.cxx.o
[  7%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dToolsDate.cxx.o
[ 10%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dCommandLineParser.cxx.o
[ 12%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dAccessionNumberValidator.cxx.o
[ 15%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dHeaderImporter.cxx.o
[ 17%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dDicomClass.cxx.o
[ 20%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dOtherDicomTags.cxx.o
[ 23%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dPatient.cxx.o
[ 25%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dStudy.cxx.o
[ 28%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dSeries.cxx.o
[ 30%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dAcquisition.cxx.o
[ 33%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dInputImporter.cxx.o
[ 35%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dInputFilter.cxx.o
[ 38%] Building CXX object src/core/CMakeFiles/nifti2dicom_core.dir/n2dInstance.cxx.o
/nifti2dicom-master/src/core/n2dInstance.cxx: In member function ‘bool n2d::Instance::Update()’:
/nifti2dicom-master/src/core/n2dInstance.cxx:62: error: ‘itksys_ios’ has not been declared
/nifti2dicom-master/src/core/n2dInstance.cxx:62: error: expected ‘;’ before ‘value’
/nifti2dicom-master/src/core/n2dInstance.cxx:63: error: ‘value’ was not declared in this scope
make[2]: *** [src/core/CMakeFiles/nifti2dicom_core.dir/n2dInstance.cxx.o] Error 1
make[1]: *** [src/core/CMakeFiles/nifti2dicom_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by drdanz** [comment]
@dominicjob Thanks for reporting this issue. I suppose you are using ITK 4.9, as according to the [release announcement](http://public.kitware.com/pipermail/community/2016-February/010755.html) "itksys_ios:: and itksys_stl:: have been removed".
I will fix it in the next few days (together with a few build issues with qt5) and I will make a new release.

**Comment by dominicjob** [comment]
Hi and thanks.

Yes I am using ITK-4.9.0.

Dom

On 10/02/2016 10:46, Daniele E. Domenichelli wrote:
>
> @dominicjob <https://github.com/dominicjob> Thanks for reporting this 
> issue. I suppose you are using ITK 4.9, as according to the release 
> announcement 
> <http://public.kitware.com/pipermail/community/2016-February/010755.html> 
> "itksys_ios:: and itksys_stl:: have been removed".
> I will fix it in the next few days (together with a few build issues 
> with qt5) and I will make a new release.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/biolab-unige/nifti2dicom/issues/32#issuecomment-182309978>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
